import { _GithubRepoIssue } from "../models/GithubRepo";

export const issuesList: _GithubRepoIssue[] = [
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1136",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1136/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1136/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1136/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1136",
      "id": 1276041704,
      "node_id": "I_kwDOA-XO7M5MDtno",
      "number": 1136,
      "title": "truffle faucet migration.sol  compile error",
      "user": {
         "login": "senonchen",
         "id": 1955733,
         "node_id": "MDQ6VXNlcjE5NTU3MzM=",
         "avatar_url": "https://avatars.githubusercontent.com/u/1955733?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/senonchen",
         "html_url": "https://github.com/senonchen",
         "followers_url": "https://api.github.com/users/senonchen/followers",
         "following_url": "https://api.github.com/users/senonchen/following{/other_user}",
         "gists_url": "https://api.github.com/users/senonchen/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/senonchen/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/senonchen/subscriptions",
         "organizations_url": "https://api.github.com/users/senonchen/orgs",
         "repos_url": "https://api.github.com/users/senonchen/repos",
         "events_url": "https://api.github.com/users/senonchen/events{/privacy}",
         "received_events_url": "https://api.github.com/users/senonchen/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-06-19T12:09:34Z",
      "updated_at": "2022-06-19T12:09:34Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "correct line below:\r\nconstructor() public {\r\n    owner = msg.sender;\r\n  }\r\n",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1136/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1136/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1135",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1135/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1135/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1135/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1135",
      "id": 1252786204,
      "node_id": "PR_kwDOA-XO7M44r6DM",
      "number": 1135,
      "title": "Marking the sender address as 'payable'",
      "user": {
         "login": "kirby88",
         "id": 65531550,
         "node_id": "MDQ6VXNlcjY1NTMxNTUw",
         "avatar_url": "https://avatars.githubusercontent.com/u/65531550?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/kirby88",
         "html_url": "https://github.com/kirby88",
         "followers_url": "https://api.github.com/users/kirby88/followers",
         "following_url": "https://api.github.com/users/kirby88/following{/other_user}",
         "gists_url": "https://api.github.com/users/kirby88/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/kirby88/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/kirby88/subscriptions",
         "organizations_url": "https://api.github.com/users/kirby88/orgs",
         "repos_url": "https://api.github.com/users/kirby88/repos",
         "events_url": "https://api.github.com/users/kirby88/events{/privacy}",
         "received_events_url": "https://api.github.com/users/kirby88/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-05-30T14:02:37Z",
      "updated_at": "2022-05-30T14:04:07Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1135",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1135",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1135.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1135.patch",
         "merged_at": null
      },
      "body": "This is not compiling with latest version of solidity https://github.com/ethereumbook/ethereumbook/blob/develop/02intro.asciidoc#a-simple-contract-a-test-ether-faucet",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1135/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1135/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1134",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1134/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1134/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1134/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1134",
      "id": 1229208345,
      "node_id": "I_kwDOA-XO7M5JRDsZ",
      "number": 1134,
      "title": "Chapter 9 - Smart Contract Security, is untranslatable on Transifex",
      "user": {
         "login": "SerafDosSantos",
         "id": 3285430,
         "node_id": "MDQ6VXNlcjMyODU0MzA=",
         "avatar_url": "https://avatars.githubusercontent.com/u/3285430?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/SerafDosSantos",
         "html_url": "https://github.com/SerafDosSantos",
         "followers_url": "https://api.github.com/users/SerafDosSantos/followers",
         "following_url": "https://api.github.com/users/SerafDosSantos/following{/other_user}",
         "gists_url": "https://api.github.com/users/SerafDosSantos/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/SerafDosSantos/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/SerafDosSantos/subscriptions",
         "organizations_url": "https://api.github.com/users/SerafDosSantos/orgs",
         "repos_url": "https://api.github.com/users/SerafDosSantos/repos",
         "events_url": "https://api.github.com/users/SerafDosSantos/events{/privacy}",
         "received_events_url": "https://api.github.com/users/SerafDosSantos/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-05-09T05:48:11Z",
      "updated_at": "2022-05-09T05:49:34Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "Hi @aantonop and team, I'm halfway completing the translation of _Mastering Ethereum_ in French (Canada).\r\n\r\nThis is a heads-up for Chapter 9, Smart Contract Security, as most of the paragraphs are manually wrapped causing too many text blocks in Transifex.com and not helping with good translation by Google Translate API in the backgrounds.\r\n\r\nI haven't made any diff between the Transifex file version and the corresponding file in this repo; I'm assuming they can be different, so I'm attaching the *CORRECTED* English file (originally from transifex.com) in this issue so it can be reloaded in Transifex.com for future translators.\r\n\r\nCheers!\r\n\r\n[for_use_ethereumbook_09smart-contracts-securitytxt_fr_CA.asciidoc.txt](https://github.com/ethereumbook/ethereumbook/files/8649018/for_use_ethereumbook_09smart-contracts-securitytxt_fr_CA.asciidoc.txt)\r\n",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1134/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1134/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1133",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1133/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1133/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1133/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1133",
      "id": 1224736286,
      "node_id": "I_kwDOA-XO7M5I__4e",
      "number": 1133,
      "title": "Fix broken link in reentrancy section from chapter 09",
      "user": {
         "login": "bananlabs",
         "id": 7208013,
         "node_id": "MDQ6VXNlcjcyMDgwMTM=",
         "avatar_url": "https://avatars.githubusercontent.com/u/7208013?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/bananlabs",
         "html_url": "https://github.com/bananlabs",
         "followers_url": "https://api.github.com/users/bananlabs/followers",
         "following_url": "https://api.github.com/users/bananlabs/following{/other_user}",
         "gists_url": "https://api.github.com/users/bananlabs/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/bananlabs/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/bananlabs/subscriptions",
         "organizations_url": "https://api.github.com/users/bananlabs/orgs",
         "repos_url": "https://api.github.com/users/bananlabs/repos",
         "events_url": "https://api.github.com/users/bananlabs/events{/privacy}",
         "received_events_url": "https://api.github.com/users/bananlabs/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-05-03T22:36:45Z",
      "updated_at": "2022-05-03T22:36:45Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "In the further reading on [reentrancy](https://github.com/ethereumbook/ethereumbook/blob/develop/09smart-contracts-security.asciidoc#reentrancy) attack the link [Ethereum Smart Contract Best Practices](http://bit.ly/2ERDMxV) is dead [404]. Please Remove or update it. ",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1133/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1133/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1132",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1132/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1132/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1132/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1132",
      "id": 1223064072,
      "node_id": "PR_kwDOA-XO7M43LTed",
      "number": 1132,
      "title": "Update to use Bee for Swarm storage, Webpack4 and Web3 1.2.9",
      "user": {
         "login": "mshearer0",
         "id": 37480681,
         "node_id": "MDQ6VXNlcjM3NDgwNjgx",
         "avatar_url": "https://avatars.githubusercontent.com/u/37480681?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/mshearer0",
         "html_url": "https://github.com/mshearer0",
         "followers_url": "https://api.github.com/users/mshearer0/followers",
         "following_url": "https://api.github.com/users/mshearer0/following{/other_user}",
         "gists_url": "https://api.github.com/users/mshearer0/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/mshearer0/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/mshearer0/subscriptions",
         "organizations_url": "https://api.github.com/users/mshearer0/orgs",
         "repos_url": "https://api.github.com/users/mshearer0/repos",
         "events_url": "https://api.github.com/users/mshearer0/events{/privacy}",
         "received_events_url": "https://api.github.com/users/mshearer0/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 1,
      "created_at": "2022-05-02T16:06:19Z",
      "updated_at": "2022-05-09T23:11:58Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1132",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1132",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1132.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1132.patch",
         "merged_at": null
      },
      "body": "Updated to Bee for Swarm storage, using Bee-js and bundled with Webpack4 and Babel v7\r\n\r\n/src/config.js also needs to updated with:\r\n\r\nBEE_POSTAGE_BATCH: 'your_batch_id'",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1132/reactions",
         "total_count": 1,
         "+1": 0,
         "-1": 0,
         "laugh": 1,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1132/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1130",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1130/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1130/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1130/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1130",
      "id": 1211319596,
      "node_id": "PR_kwDOA-XO7M42ktWv",
      "number": 1130,
      "title": "Fix Appendix E. web3.js Tutorial and the corresponding source code",
      "user": {
         "login": "nobutoba",
         "id": 44864310,
         "node_id": "MDQ6VXNlcjQ0ODY0MzEw",
         "avatar_url": "https://avatars.githubusercontent.com/u/44864310?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nobutoba",
         "html_url": "https://github.com/nobutoba",
         "followers_url": "https://api.github.com/users/nobutoba/followers",
         "following_url": "https://api.github.com/users/nobutoba/following{/other_user}",
         "gists_url": "https://api.github.com/users/nobutoba/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nobutoba/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nobutoba/subscriptions",
         "organizations_url": "https://api.github.com/users/nobutoba/orgs",
         "repos_url": "https://api.github.com/users/nobutoba/repos",
         "events_url": "https://api.github.com/users/nobutoba/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nobutoba/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-04-21T17:07:41Z",
      "updated_at": "2022-04-21T17:07:41Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1130",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1130",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1130.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1130.patch",
         "merged_at": null
      },
      "body": "Currently, the command\r\n\r\n```shell\r\n$ node code/web3js/web3js_demo/web3-contract-basic-interaction.js \\\r\n  --infuraFileToken /path/to/file/with/infura_token\r\n```\r\n\r\nissues an error message like:\r\n\r\n```shell\r\nUnhandled rejection SyntaxError: Unexpected token I in JSON at position 0\r\n```\r\n\r\nThe main purpose of this pull request is to fix this problem.\r\nIn a nutshell, the error above occurs because the base API call URL through Etherscan\r\nchanged from <http://kovan.etherscan.io> to <http://api-kovan.etherscan.io>.\r\n",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1130/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1130/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1129",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1129/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1129/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1129/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1129",
      "id": 1206230786,
      "node_id": "I_kwDOA-XO7M5H5Z8C",
      "number": 1129,
      "title": "Ethereum",
      "user": {
         "login": "afanashraf",
         "id": 93472583,
         "node_id": "U_kgDOBZJHRw",
         "avatar_url": "https://avatars.githubusercontent.com/u/93472583?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/afanashraf",
         "html_url": "https://github.com/afanashraf",
         "followers_url": "https://api.github.com/users/afanashraf/followers",
         "following_url": "https://api.github.com/users/afanashraf/following{/other_user}",
         "gists_url": "https://api.github.com/users/afanashraf/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/afanashraf/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/afanashraf/subscriptions",
         "organizations_url": "https://api.github.com/users/afanashraf/orgs",
         "repos_url": "https://api.github.com/users/afanashraf/repos",
         "events_url": "https://api.github.com/users/afanashraf/events{/privacy}",
         "received_events_url": "https://api.github.com/users/afanashraf/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-04-16T22:41:48Z",
      "updated_at": "2022-04-16T22:41:48Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": null,
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1129/reactions",
         "total_count": 1,
         "+1": 0,
         "-1": 1,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1129/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1128",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1128/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1128/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1128/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1128",
      "id": 1206157605,
      "node_id": "PR_kwDOA-XO7M42UVWc",
      "number": 1128,
      "title": "Update to web3 1.2.9",
      "user": {
         "login": "mshearer0",
         "id": 37480681,
         "node_id": "MDQ6VXNlcjM3NDgwNjgx",
         "avatar_url": "https://avatars.githubusercontent.com/u/37480681?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/mshearer0",
         "html_url": "https://github.com/mshearer0",
         "followers_url": "https://api.github.com/users/mshearer0/followers",
         "following_url": "https://api.github.com/users/mshearer0/following{/other_user}",
         "gists_url": "https://api.github.com/users/mshearer0/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/mshearer0/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/mshearer0/subscriptions",
         "organizations_url": "https://api.github.com/users/mshearer0/orgs",
         "repos_url": "https://api.github.com/users/mshearer0/repos",
         "events_url": "https://api.github.com/users/mshearer0/events{/privacy}",
         "received_events_url": "https://api.github.com/users/mshearer0/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-04-16T16:30:02Z",
      "updated_at": "2022-04-16T16:30:02Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1128",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1128",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1128.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1128.patch",
         "merged_at": null
      },
      "body": "Update to web3 @ 1.2.9. Further update to swarm bee required",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1128/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1128/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1127",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1127/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1127/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1127/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1127",
      "id": 1205808959,
      "node_id": "I_kwDOA-XO7M5H3y8_",
      "number": 1127,
      "title": "Unable to finalize auction",
      "user": {
         "login": "mshearer0",
         "id": 37480681,
         "node_id": "MDQ6VXNlcjM3NDgwNjgx",
         "avatar_url": "https://avatars.githubusercontent.com/u/37480681?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/mshearer0",
         "html_url": "https://github.com/mshearer0",
         "followers_url": "https://api.github.com/users/mshearer0/followers",
         "following_url": "https://api.github.com/users/mshearer0/following{/other_user}",
         "gists_url": "https://api.github.com/users/mshearer0/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/mshearer0/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/mshearer0/subscriptions",
         "organizations_url": "https://api.github.com/users/mshearer0/orgs",
         "repos_url": "https://api.github.com/users/mshearer0/repos",
         "events_url": "https://api.github.com/users/mshearer0/events{/privacy}",
         "received_events_url": "https://api.github.com/users/mshearer0/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-04-15T19:18:30Z",
      "updated_at": "2022-04-15T19:18:30Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "To finalize an auction you need to be AuctionOwner and be the LastBidder. \r\n\r\n```\r\n<v-btn @click=\"finalizeAuction(auc.id)\" :disabled=\"!isAuctionOwner(auc) || !isLastBidder(auc)\" style=\" margin:0; width:100%;\" color=\"teal\" dark> Finalize Auction </v-btn>\r\n```\r\nAs you can't Bid on your own auction this seems an impossible condition. \r\n\r\n```\r\n<v-btn :disabled=\"isAuctionOwner(auc) || !auc.active\" @click=\"bidModal = true\" style=\" margin:0; width:100%;\" color=\"teal\" dark> Bid now </v-btn>\r\n```\r\n\r\n",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1127/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1127/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1126",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1126/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1126/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1126/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1126",
      "id": 1192814821,
      "node_id": "PR_kwDOA-XO7M41o7O5",
      "number": 1126,
      "title": "Gas Consideration for Testnet",
      "user": {
         "login": "ololade97",
         "id": 53153510,
         "node_id": "MDQ6VXNlcjUzMTUzNTEw",
         "avatar_url": "https://avatars.githubusercontent.com/u/53153510?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/ololade97",
         "html_url": "https://github.com/ololade97",
         "followers_url": "https://api.github.com/users/ololade97/followers",
         "following_url": "https://api.github.com/users/ololade97/following{/other_user}",
         "gists_url": "https://api.github.com/users/ololade97/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/ololade97/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/ololade97/subscriptions",
         "organizations_url": "https://api.github.com/users/ololade97/orgs",
         "repos_url": "https://api.github.com/users/ololade97/repos",
         "events_url": "https://api.github.com/users/ololade97/events{/privacy}",
         "received_events_url": "https://api.github.com/users/ololade97/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-04-05T08:38:08Z",
      "updated_at": "2022-04-05T08:38:08Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1126",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1126",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1126.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1126.patch",
         "merged_at": null
      },
      "body": "A testnet now deducts a transaction fee, that's gas. A free ether will not be sent to another testnet address without gas. ",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1126/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1126/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1125",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1125/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1125/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1125/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1125",
      "id": 1174277086,
      "node_id": "PR_kwDOA-XO7M40sJOJ",
      "number": 1125,
      "title": "Fix contract successful termination explanation",
      "user": {
         "login": "Bielwenass",
         "id": 15036469,
         "node_id": "MDQ6VXNlcjE1MDM2NDY5",
         "avatar_url": "https://avatars.githubusercontent.com/u/15036469?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/Bielwenass",
         "html_url": "https://github.com/Bielwenass",
         "followers_url": "https://api.github.com/users/Bielwenass/followers",
         "following_url": "https://api.github.com/users/Bielwenass/following{/other_user}",
         "gists_url": "https://api.github.com/users/Bielwenass/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/Bielwenass/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/Bielwenass/subscriptions",
         "organizations_url": "https://api.github.com/users/Bielwenass/orgs",
         "repos_url": "https://api.github.com/users/Bielwenass/repos",
         "events_url": "https://api.github.com/users/Bielwenass/events{/privacy}",
         "received_events_url": "https://api.github.com/users/Bielwenass/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-03-19T14:24:59Z",
      "updated_at": "2022-03-19T14:24:59Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1125",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1125",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1125.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1125.patch",
         "merged_at": null
      },
      "body": "I believe there is some erroneous wording here. Surely some changes might not be recorded when there are errors propagated, and all changes are recorded when there are none, not the other way around.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1125/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1125/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1123",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1123/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1123/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1123/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1123",
      "id": 1173312360,
      "node_id": "I_kwDOA-XO7M5F71No",
      "number": 1123,
      "title": "Updating Auction Dapp to Web3 1.2.9 (added Bee with Webpack4 and Babel7)",
      "user": {
         "login": "mshearer0",
         "id": 37480681,
         "node_id": "MDQ6VXNlcjM3NDgwNjgx",
         "avatar_url": "https://avatars.githubusercontent.com/u/37480681?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/mshearer0",
         "html_url": "https://github.com/mshearer0",
         "followers_url": "https://api.github.com/users/mshearer0/followers",
         "following_url": "https://api.github.com/users/mshearer0/following{/other_user}",
         "gists_url": "https://api.github.com/users/mshearer0/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/mshearer0/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/mshearer0/subscriptions",
         "organizations_url": "https://api.github.com/users/mshearer0/orgs",
         "repos_url": "https://api.github.com/users/mshearer0/repos",
         "events_url": "https://api.github.com/users/mshearer0/events{/privacy}",
         "received_events_url": "https://api.github.com/users/mshearer0/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 4,
      "created_at": "2022-03-18T08:13:57Z",
      "updated_at": "2022-05-02T16:26:38Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "I had to make a few changes to Auction Dapp to run with current Web3:\r\n\r\nWeb3 1.2.9\r\nNode 16.14.0\r\nNPM 8.5.2\r\n\r\n1. Update main.js as\r\n\r\n```\r\n\tif(typeof web3 !== 'undefined') {    \r\n            if (window.ethereum) {\r\n                web3 = new Web3_1(window.ethereum)\r\n            }\r\n            this.$auctionRepoInstance.setWeb3(web3)\r\n            this.$deedRepoInstance.setWeb3(web3)    \r\n\r\n            store.setMetamaskInstalled()\r\n\r\n            web3.eth.net.getId().then(netId => { store.setNetworkId(netId) })\r\n```\r\n2. Update App.vue to use web3.utils.BN:\r\n\r\n```\r\n// get random deedid\r\n            this.deed.deedId = new web3.utils.BN(`${this.$root.$data.globalState.getRandomInt(123456789,999999999)}${this.$roo\r\nt.$data.globalState.getRandomInt(123456789,999999999)}`)\r\n```\r\n\r\n3. In Models add 'new' to initialise contract:\r\n\r\n```\r\nthis.contractInstance = new this.web3.eth.Contract(Config.DEEDREPOSITORY_ABI,Config.DEEDREPOSITORY_ADDRESS)\r\n```\r\n\r\n4.  In Models update all the contract fn calls to either .send (if write) or .call (if read only) in this format:\r\n\r\n```\r\nthis.contractInstance.methods.registerDeed(deedId, deedURI).send({from: this.account, gas: this.gas }, function(err,\r\n transaction) {    \r\n```\r\n5. In Models update all the watchers as:\r\n\r\n```\r\n    async watchIfCreated(cb) {\r\n        const currentBlock = await this.getCurrentBlock()\r\n        this.contractInstance.events.DeedRegistered({\r\n            filter: {}, \r\n            fromBlock: currentBlock - 1\r\n            },  cb)\r\n    }\r\n```\r\n\r\n6. Update .fromWei() to utils.fromWei()\r\n\r\n7. If using Ropsten config.js should be of format:\r\n\r\nJSONRPC_ENDPOINT: 'https://ropsten.infura.io/v3/_your_id',\r\nJSONRPC_WS_ENDPOINT: 'wss://ropsten.infura.io/ws/v3/_your_id',\r\n\r\nNote Ganache-ui doesn't support websockets so cant be used for testing. Ganache-cli does.\r\n\r\n8. In backend the truffle test needed to be updated:\r\n\r\n```\r\nit(\"It should register a deed with id: 123456789\", async () => {\r\n        await instance.registerDeed(123456789,\"test\");\r\n        let ownerOfDeed = await instance.exists(123456789);\r\n        assert.equal(ownerOfDeed.valueOf(), true , `Result should be true`);\r\n    });\r\n```\r\n\r\nMake sure DEEDREPOSITORY_ADDRESS and AUCTIONREPOSITORY_ADDRESS are the addresses of your contracts after deployment and that JSON files from backend/build/contracts match.\r\n\r\nSwarm bee needs to be updated so have commented these lines out for now, leaving \r\n```\r\nlet imageUrl = \"\";\r\n```\r\n\r\nHappy to submit pull request\r\n",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1123/reactions",
         "total_count": 1,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 1,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1123/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1119",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1119/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1119/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1119/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1119",
      "id": 1155767316,
      "node_id": "I_kwDOA-XO7M5E45wU",
      "number": 1119,
      "title": "METFaucet Deployment",
      "user": {
         "login": "mshearer0",
         "id": 37480681,
         "node_id": "MDQ6VXNlcjM3NDgwNjgx",
         "avatar_url": "https://avatars.githubusercontent.com/u/37480681?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/mshearer0",
         "html_url": "https://github.com/mshearer0",
         "followers_url": "https://api.github.com/users/mshearer0/followers",
         "following_url": "https://api.github.com/users/mshearer0/following{/other_user}",
         "gists_url": "https://api.github.com/users/mshearer0/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/mshearer0/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/mshearer0/subscriptions",
         "organizations_url": "https://api.github.com/users/mshearer0/orgs",
         "repos_url": "https://api.github.com/users/mshearer0/repos",
         "events_url": "https://api.github.com/users/mshearer0/events{/privacy}",
         "received_events_url": "https://api.github.com/users/mshearer0/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-03-01T20:10:20Z",
      "updated_at": "2022-03-01T20:10:20Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "To deploy to local Ganache I had to modify ethereumbook/code/truffle/METoken_METFaucet/migrations/2_deploy_contracts.js as:\r\n\r\n```\r\nvar METoken = artifacts.require(\"METoken\");\r\nvar METFaucet = artifacts.require(\"METFaucet\");\r\n\r\nmodule.exports = async function(deployer) {\r\n\r\n        var accounts = await web3.eth.getAccounts();\r\n        var owner = accounts[0];\r\n        \r\n        await deployer.deploy(METoken, {from: owner});\r\n        await deployer.deploy(METFaucet, METoken.address, owner);\r\n}\r\n```\r\nand replace web3.eth.accounts[1] with accounts[1] in the console commands.\r\n\r\ntruffle-config.js :\r\n```\r\nmodule.exports = {\r\n       compilers: {\r\n             solc: {\r\n                   version: \"0.4.24\"\r\n              }\r\n        },\r\n\r\n        networks: {\r\n                ganache: { // Ganache local test RPC blockchain\r\n                        network_id: \"5777\",\r\n                        host: \"localhost\",\r\n                        port: 7545,\r\n                        gas: 6721975,\r\n                }\r\n        }\r\n};\r\n```\r\n",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1119/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1119/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1118",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1118/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1118/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1118/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1118",
      "id": 1150337636,
      "node_id": "PR_kwDOA-XO7M4zdakr",
      "number": 1118,
      "title": "Update 07smart-contracts-solidity.asciidoc following EIP-3529",
      "user": {
         "login": "mbiss10",
         "id": 50077908,
         "node_id": "MDQ6VXNlcjUwMDc3OTA4",
         "avatar_url": "https://avatars.githubusercontent.com/u/50077908?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/mbiss10",
         "html_url": "https://github.com/mbiss10",
         "followers_url": "https://api.github.com/users/mbiss10/followers",
         "following_url": "https://api.github.com/users/mbiss10/following{/other_user}",
         "gists_url": "https://api.github.com/users/mbiss10/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/mbiss10/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/mbiss10/subscriptions",
         "organizations_url": "https://api.github.com/users/mbiss10/orgs",
         "repos_url": "https://api.github.com/users/mbiss10/repos",
         "events_url": "https://api.github.com/users/mbiss10/events{/privacy}",
         "received_events_url": "https://api.github.com/users/mbiss10/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-02-25T11:25:37Z",
      "updated_at": "2022-02-25T11:25:37Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1118",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1118",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1118.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1118.patch",
         "merged_at": null
      },
      "body": "Remove mention of gas refunds for SELFDESTRUCT following EIP-3529 (https://eips.ethereum.org/EIPS/eip-3529).\r\n\r\nExcised line:\r\n> (((\"negative gas\")))That operation costs “negative gas,” a gas refund, thereby incentivizing the release of network client resources from the deletion of stored state.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1118/reactions",
         "total_count": 1,
         "+1": 1,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1118/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1116",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1116/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1116/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1116/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1116",
      "id": 1144745528,
      "node_id": "I_kwDOA-XO7M5EO244",
      "number": 1116,
      "title": "broken link",
      "user": {
         "login": "php4fan",
         "id": 13969584,
         "node_id": "MDQ6VXNlcjEzOTY5NTg0",
         "avatar_url": "https://avatars.githubusercontent.com/u/13969584?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/php4fan",
         "html_url": "https://github.com/php4fan",
         "followers_url": "https://api.github.com/users/php4fan/followers",
         "following_url": "https://api.github.com/users/php4fan/following{/other_user}",
         "gists_url": "https://api.github.com/users/php4fan/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/php4fan/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/php4fan/subscriptions",
         "organizations_url": "https://api.github.com/users/php4fan/orgs",
         "repos_url": "https://api.github.com/users/php4fan/repos",
         "events_url": "https://api.github.com/users/php4fan/events{/privacy}",
         "received_events_url": "https://api.github.com/users/php4fan/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 2,
      "created_at": "2022-02-19T15:09:38Z",
      "updated_at": "2022-03-16T11:28:59Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "At https://github.com/ethereumbook/ethereumbook/blob/develop/07smart-contracts-solidity.asciidoc#writing-a-simple-solidity-program\r\n\r\n> In [[intro_chapter]](https://github.com/ethereumbook/ethereumbook/blob/develop/07smart-contracts-solidity.asciidoc#intro_chapter), we wrote our first Solidity program\r\n\r\nThat [intro_chapter] links to https://github.com/ethereumbook/ethereumbook/blob/develop/07smart-contracts-solidity.asciidoc#intro_chapter which does not exist.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1116/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1116/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1113",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1113/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1113/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1113/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1113",
      "id": 1140980166,
      "node_id": "I_kwDOA-XO7M5EAfnG",
      "number": 1113,
      "title": "Translate to Chinese.",
      "user": {
         "login": "ethwillupto10000",
         "id": 20765145,
         "node_id": "MDQ6VXNlcjIwNzY1MTQ1",
         "avatar_url": "https://avatars.githubusercontent.com/u/20765145?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/ethwillupto10000",
         "html_url": "https://github.com/ethwillupto10000",
         "followers_url": "https://api.github.com/users/ethwillupto10000/followers",
         "following_url": "https://api.github.com/users/ethwillupto10000/following{/other_user}",
         "gists_url": "https://api.github.com/users/ethwillupto10000/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/ethwillupto10000/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/ethwillupto10000/subscriptions",
         "organizations_url": "https://api.github.com/users/ethwillupto10000/orgs",
         "repos_url": "https://api.github.com/users/ethwillupto10000/repos",
         "events_url": "https://api.github.com/users/ethwillupto10000/events{/privacy}",
         "received_events_url": "https://api.github.com/users/ethwillupto10000/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-02-17T07:43:08Z",
      "updated_at": "2022-02-17T07:43:08Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": null,
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1113/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1113/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1111",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1111/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1111/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1111/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1111",
      "id": 1127066572,
      "node_id": "PR_kwDOA-XO7M4yOcOu",
      "number": 1111,
      "title": "Update 09smart-contracts-security.asciidoc",
      "user": {
         "login": "HamzaRaza786",
         "id": 49732070,
         "node_id": "MDQ6VXNlcjQ5NzMyMDcw",
         "avatar_url": "https://avatars.githubusercontent.com/u/49732070?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/HamzaRaza786",
         "html_url": "https://github.com/HamzaRaza786",
         "followers_url": "https://api.github.com/users/HamzaRaza786/followers",
         "following_url": "https://api.github.com/users/HamzaRaza786/following{/other_user}",
         "gists_url": "https://api.github.com/users/HamzaRaza786/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/HamzaRaza786/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/HamzaRaza786/subscriptions",
         "organizations_url": "https://api.github.com/users/HamzaRaza786/orgs",
         "repos_url": "https://api.github.com/users/HamzaRaza786/repos",
         "events_url": "https://api.github.com/users/HamzaRaza786/events{/privacy}",
         "received_events_url": "https://api.github.com/users/HamzaRaza786/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-02-08T10:29:26Z",
      "updated_at": "2022-02-08T10:29:26Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1111",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1111",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1111.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1111.patch",
         "merged_at": null
      },
      "body": "I changed the URL address of Ethereum best practices as the first one directed to page 404 not found.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1111/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1111/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1110",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1110/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1110/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1110/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1110",
      "id": 1119198695,
      "node_id": "PR_kwDOA-XO7M4x02p3",
      "number": 1110,
      "title": "Fix broken links in chapter 9",
      "user": {
         "login": "davidkathoh",
         "id": 18406487,
         "node_id": "MDQ6VXNlcjE4NDA2NDg3",
         "avatar_url": "https://avatars.githubusercontent.com/u/18406487?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/davidkathoh",
         "html_url": "https://github.com/davidkathoh",
         "followers_url": "https://api.github.com/users/davidkathoh/followers",
         "following_url": "https://api.github.com/users/davidkathoh/following{/other_user}",
         "gists_url": "https://api.github.com/users/davidkathoh/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/davidkathoh/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/davidkathoh/subscriptions",
         "organizations_url": "https://api.github.com/users/davidkathoh/orgs",
         "repos_url": "https://api.github.com/users/davidkathoh/repos",
         "events_url": "https://api.github.com/users/davidkathoh/events{/privacy}",
         "received_events_url": "https://api.github.com/users/davidkathoh/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-01-31T09:45:03Z",
      "updated_at": "2022-01-31T09:45:03Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1110",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1110",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1110.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1110.patch",
         "merged_at": null
      },
      "body": "1. In the section about DELEGATECALL and  Uninitialized Storage Pointers, the links to Layout of state variables in storage and layout in memory were redirecting to no existent page in solidity docs.\r\n\r\n2. The link to “History of\r\nEthereum Security Vulnerabilities, Hacks and Their Fixes” in  Block Timestamp Manipulation and Constructors sections  with Care were referencing a different subject on the blog",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1110/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1110/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1109",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1109/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1109/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1109/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1109",
      "id": 1116909514,
      "node_id": "PR_kwDOA-XO7M4xtjgT",
      "number": 1109,
      "title": "Grammar fix in 07smart-contracts-solidity",
      "user": {
         "login": "liamjsc",
         "id": 12700715,
         "node_id": "MDQ6VXNlcjEyNzAwNzE1",
         "avatar_url": "https://avatars.githubusercontent.com/u/12700715?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/liamjsc",
         "html_url": "https://github.com/liamjsc",
         "followers_url": "https://api.github.com/users/liamjsc/followers",
         "following_url": "https://api.github.com/users/liamjsc/following{/other_user}",
         "gists_url": "https://api.github.com/users/liamjsc/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/liamjsc/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/liamjsc/subscriptions",
         "organizations_url": "https://api.github.com/users/liamjsc/orgs",
         "repos_url": "https://api.github.com/users/liamjsc/repos",
         "events_url": "https://api.github.com/users/liamjsc/events{/privacy}",
         "received_events_url": "https://api.github.com/users/liamjsc/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-01-28T01:33:31Z",
      "updated_at": "2022-01-28T01:33:31Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1109",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1109",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1109.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1109.patch",
         "merged_at": null
      },
      "body": "Fixing subject-verb agreement in point (4) \"...in a manner that does not propagate...\"",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1109/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1109/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1107",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1107/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1107/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1107/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1107",
      "id": 1101430959,
      "node_id": "I_kwDOA-XO7M5BpoCv",
      "number": 1107,
      "title": "Files Not present on the mentioned Directory",
      "user": {
         "login": "delixus-valliammal1",
         "id": 94059532,
         "node_id": "U_kgDOBZs8DA",
         "avatar_url": "https://avatars.githubusercontent.com/u/94059532?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/delixus-valliammal1",
         "html_url": "https://github.com/delixus-valliammal1",
         "followers_url": "https://api.github.com/users/delixus-valliammal1/followers",
         "following_url": "https://api.github.com/users/delixus-valliammal1/following{/other_user}",
         "gists_url": "https://api.github.com/users/delixus-valliammal1/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/delixus-valliammal1/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/delixus-valliammal1/subscriptions",
         "organizations_url": "https://api.github.com/users/delixus-valliammal1/orgs",
         "repos_url": "https://api.github.com/users/delixus-valliammal1/repos",
         "events_url": "https://api.github.com/users/delixus-valliammal1/events{/privacy}",
         "received_events_url": "https://api.github.com/users/delixus-valliammal1/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-01-13T09:28:11Z",
      "updated_at": "2022-01-13T09:28:11Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "There is lot of files are not present.\r\n\r\nWe need this files of solidity, so that this book can be used nicely\r\nimport './SampleToken.sol';\r\nimport 'openzeppelin-solidity/contracts/crowdsale/emission/MintedCrowdsale.sol';\r\nimport 'openzeppelin-solidity/contracts/crowdsale/ \\\r\n  distribution/PostDeliveryCrowdsale.sol';\r\n\r\nWhere is MintedCrowdSale.sol, and PostDeliveryCrowdsale.sol?\r\n\r\nCan you please clarify?\r\n\r\nthanks\r\n",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1107/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1107/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1106",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1106/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1106/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1106/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1106",
      "id": 1100590783,
      "node_id": "PR_kwDOA-XO7M4w3uVM",
      "number": 1106,
      "title": "Chapter 9: update non existing link",
      "user": {
         "login": "MrLaki5",
         "id": 18501851,
         "node_id": "MDQ6VXNlcjE4NTAxODUx",
         "avatar_url": "https://avatars.githubusercontent.com/u/18501851?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/MrLaki5",
         "html_url": "https://github.com/MrLaki5",
         "followers_url": "https://api.github.com/users/MrLaki5/followers",
         "following_url": "https://api.github.com/users/MrLaki5/following{/other_user}",
         "gists_url": "https://api.github.com/users/MrLaki5/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/MrLaki5/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/MrLaki5/subscriptions",
         "organizations_url": "https://api.github.com/users/MrLaki5/orgs",
         "repos_url": "https://api.github.com/users/MrLaki5/repos",
         "events_url": "https://api.github.com/users/MrLaki5/events{/privacy}",
         "received_events_url": "https://api.github.com/users/MrLaki5/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2022-01-12T17:13:36Z",
      "updated_at": "2022-01-12T17:13:36Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1106",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1106",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1106.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1106.patch",
         "merged_at": null
      },
      "body": "Given link is non existing. I tried to find referenced content on https://vitalik.ca/ but was not successful. It seems to me that it has been removed.\r\n\r\nI found referenced content on web-archive and linked it, as users in future will again be able to read it from there.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1106/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1106/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1105",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1105/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1105/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1105/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1105",
      "id": 1091688928,
      "node_id": "I_kwDOA-XO7M5BEdng",
      "number": 1105,
      "title": "Link is dead",
      "user": {
         "login": "CaledoniaProject",
         "id": 1357701,
         "node_id": "MDQ6VXNlcjEzNTc3MDE=",
         "avatar_url": "https://avatars.githubusercontent.com/u/1357701?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/CaledoniaProject",
         "html_url": "https://github.com/CaledoniaProject",
         "followers_url": "https://api.github.com/users/CaledoniaProject/followers",
         "following_url": "https://api.github.com/users/CaledoniaProject/following{/other_user}",
         "gists_url": "https://api.github.com/users/CaledoniaProject/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/CaledoniaProject/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/CaledoniaProject/subscriptions",
         "organizations_url": "https://api.github.com/users/CaledoniaProject/orgs",
         "repos_url": "https://api.github.com/users/CaledoniaProject/repos",
         "events_url": "https://api.github.com/users/CaledoniaProject/events{/privacy}",
         "received_events_url": "https://api.github.com/users/CaledoniaProject/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2021-12-31T23:40:21Z",
      "updated_at": "2021-12-31T23:40:21Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "On page https://github.com/ethereumbook/ethereumbook/blob/develop/08smart-contracts-vyper.asciidoc, quote:\r\n\r\n> Firstly, Vyper provides a SafeMath equivalent that includes the necessary exception cases for integer arithmetic\r\n\r\nThe referenced link is 404 now: http://bit.ly/2PuDfpB",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1105/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1105/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1102",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1102/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1102/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1102/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1102",
      "id": 1083780182,
      "node_id": "I_kwDOA-XO7M5AmSxW",
      "number": 1102,
      "title": "Printed hardcover edition 2022 ?",
      "user": {
         "login": "baermathias",
         "id": 45003352,
         "node_id": "MDQ6VXNlcjQ1MDAzMzUy",
         "avatar_url": "https://avatars.githubusercontent.com/u/45003352?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/baermathias",
         "html_url": "https://github.com/baermathias",
         "followers_url": "https://api.github.com/users/baermathias/followers",
         "following_url": "https://api.github.com/users/baermathias/following{/other_user}",
         "gists_url": "https://api.github.com/users/baermathias/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/baermathias/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/baermathias/subscriptions",
         "organizations_url": "https://api.github.com/users/baermathias/orgs",
         "repos_url": "https://api.github.com/users/baermathias/repos",
         "events_url": "https://api.github.com/users/baermathias/events{/privacy}",
         "received_events_url": "https://api.github.com/users/baermathias/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2021-12-18T08:19:51Z",
      "updated_at": "2021-12-18T08:19:51Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "Are there any plans to release a new printed edition? The latest is from 2018 and more than two years old, which is considered as really old in the crypto space. Many, many things have changed since the 2018 version.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1102/reactions",
         "total_count": 5,
         "+1": 5,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1102/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1099",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1099/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1099/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1099/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1099",
      "id": 1078023567,
      "node_id": "PR_kwDOA-XO7M4vu6_C",
      "number": 1099,
      "title": "Update several outdated parts from Chapter 2",
      "user": {
         "login": "0xEndeavor",
         "id": 88470528,
         "node_id": "MDQ6VXNlcjg4NDcwNTI4",
         "avatar_url": "https://avatars.githubusercontent.com/u/88470528?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/0xEndeavor",
         "html_url": "https://github.com/0xEndeavor",
         "followers_url": "https://api.github.com/users/0xEndeavor/followers",
         "following_url": "https://api.github.com/users/0xEndeavor/following{/other_user}",
         "gists_url": "https://api.github.com/users/0xEndeavor/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/0xEndeavor/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/0xEndeavor/subscriptions",
         "organizations_url": "https://api.github.com/users/0xEndeavor/orgs",
         "repos_url": "https://api.github.com/users/0xEndeavor/repos",
         "events_url": "https://api.github.com/users/0xEndeavor/events{/privacy}",
         "received_events_url": "https://api.github.com/users/0xEndeavor/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2021-12-13T02:52:17Z",
      "updated_at": "2022-03-24T21:03:00Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1099",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1099",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1099.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1099.patch",
         "merged_at": null
      },
      "body": "I've updated and added a number of screenshots and wording to clean up some of the outdated content. Focused on the Getting Started with Metamask and initial Remix sections.\r\n\r\nThere's still quite a bit to be done. However, it requires a broader content rewrite to handle issues (out of my scope) such as the broken Metamask Ropsten faucet. \r\n\r\nPlease let me know if there are any questions or feedback.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1099/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1099/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1096",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1096/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1096/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1096/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1096",
      "id": 1060536392,
      "node_id": "PR_kwDOA-XO7M4u3xjS",
      "number": 1096,
      "title": "Fix script",
      "user": {
         "login": "samlaf",
         "id": 9342524,
         "node_id": "MDQ6VXNlcjkzNDI1MjQ=",
         "avatar_url": "https://avatars.githubusercontent.com/u/9342524?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/samlaf",
         "html_url": "https://github.com/samlaf",
         "followers_url": "https://api.github.com/users/samlaf/followers",
         "following_url": "https://api.github.com/users/samlaf/following{/other_user}",
         "gists_url": "https://api.github.com/users/samlaf/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/samlaf/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/samlaf/subscriptions",
         "organizations_url": "https://api.github.com/users/samlaf/orgs",
         "repos_url": "https://api.github.com/users/samlaf/repos",
         "events_url": "https://api.github.com/users/samlaf/events{/privacy}",
         "received_events_url": "https://api.github.com/users/samlaf/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2021-11-22T19:54:56Z",
      "updated_at": "2021-11-22T19:54:56Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1096",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1096",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1096.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1096.patch",
         "merged_at": null
      },
      "body": "the ethereumjs-tx was updated (and is now part of the ethereumjs monorepo (hence the @etheremjs/tx import)\r\nalso the tx.sign() function now returns a new signed transaction, instead of signing in place.\r\nalso changed the last console.log() to look like the first one.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1096/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1096/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1094",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1094/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1094/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1094/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1094",
      "id": 1040835333,
      "node_id": "PR_kwDOA-XO7M4t6NBh",
      "number": 1094,
      "title": "Updated 02intro.asciidoc with an alternative faucet",
      "user": {
         "login": "sudotman",
         "id": 68228813,
         "node_id": "MDQ6VXNlcjY4MjI4ODEz",
         "avatar_url": "https://avatars.githubusercontent.com/u/68228813?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/sudotman",
         "html_url": "https://github.com/sudotman",
         "followers_url": "https://api.github.com/users/sudotman/followers",
         "following_url": "https://api.github.com/users/sudotman/following{/other_user}",
         "gists_url": "https://api.github.com/users/sudotman/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/sudotman/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/sudotman/subscriptions",
         "organizations_url": "https://api.github.com/users/sudotman/orgs",
         "repos_url": "https://api.github.com/users/sudotman/repos",
         "events_url": "https://api.github.com/users/sudotman/events{/privacy}",
         "received_events_url": "https://api.github.com/users/sudotman/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2021-11-01T07:03:20Z",
      "updated_at": "2021-11-01T07:03:20Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1094",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1094",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1094.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1094.patch",
         "merged_at": null
      },
      "body": "MetaMask test faucet tends to glitch out a lot of times and not send any ether. An alternative faucet would be helpful.",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1094/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1094/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1049",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1049/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1049/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1049/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/issues/1049",
      "id": 1027940745,
      "node_id": "I_kwDOA-XO7M49RSGJ",
      "number": 1049,
      "title": "Chapter 3 should also include Nethermind's Ethereum 1 client",
      "user": {
         "login": "dB2510",
         "id": 37813203,
         "node_id": "MDQ6VXNlcjM3ODEzMjAz",
         "avatar_url": "https://avatars.githubusercontent.com/u/37813203?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/dB2510",
         "html_url": "https://github.com/dB2510",
         "followers_url": "https://api.github.com/users/dB2510/followers",
         "following_url": "https://api.github.com/users/dB2510/following{/other_user}",
         "gists_url": "https://api.github.com/users/dB2510/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/dB2510/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/dB2510/subscriptions",
         "organizations_url": "https://api.github.com/users/dB2510/orgs",
         "repos_url": "https://api.github.com/users/dB2510/repos",
         "events_url": "https://api.github.com/users/dB2510/events{/privacy}",
         "received_events_url": "https://api.github.com/users/dB2510/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2021-10-16T03:43:43Z",
      "updated_at": "2021-10-16T03:43:43Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": null,
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1049/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1049/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1048",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1048/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1048/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1048/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1048",
      "id": 1021770992,
      "node_id": "PR_kwDOA-XO7M4s-aU8",
      "number": 1048,
      "title": "v3 added to the infura host url to match the endpoints generated by infura.io",
      "user": {
         "login": "adrianpusty",
         "id": 51136868,
         "node_id": "MDQ6VXNlcjUxMTM2ODY4",
         "avatar_url": "https://avatars.githubusercontent.com/u/51136868?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/adrianpusty",
         "html_url": "https://github.com/adrianpusty",
         "followers_url": "https://api.github.com/users/adrianpusty/followers",
         "following_url": "https://api.github.com/users/adrianpusty/following{/other_user}",
         "gists_url": "https://api.github.com/users/adrianpusty/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/adrianpusty/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/adrianpusty/subscriptions",
         "organizations_url": "https://api.github.com/users/adrianpusty/orgs",
         "repos_url": "https://api.github.com/users/adrianpusty/repos",
         "events_url": "https://api.github.com/users/adrianpusty/events{/privacy}",
         "received_events_url": "https://api.github.com/users/adrianpusty/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 1,
      "created_at": "2021-10-09T18:11:17Z",
      "updated_at": "2021-10-10T08:40:40Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1048",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1048",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1048.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1048.patch",
         "merged_at": null
      },
      "body": "…",
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1048/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1048/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1047",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1047/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1047/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1047/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1047",
      "id": 1018909706,
      "node_id": "PR_kwDOA-XO7M4s1YoR",
      "number": 1047,
      "title": "Updates date for pi day, 2017",
      "user": {
         "login": "sulav",
         "id": 1301095,
         "node_id": "MDQ6VXNlcjEzMDEwOTU=",
         "avatar_url": "https://avatars.githubusercontent.com/u/1301095?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/sulav",
         "html_url": "https://github.com/sulav",
         "followers_url": "https://api.github.com/users/sulav/followers",
         "following_url": "https://api.github.com/users/sulav/following{/other_user}",
         "gists_url": "https://api.github.com/users/sulav/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/sulav/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/sulav/subscriptions",
         "organizations_url": "https://api.github.com/users/sulav/orgs",
         "repos_url": "https://api.github.com/users/sulav/repos",
         "events_url": "https://api.github.com/users/sulav/events{/privacy}",
         "received_events_url": "https://api.github.com/users/sulav/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2021-10-06T18:15:41Z",
      "updated_at": "2021-10-06T18:15:41Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1047",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1047",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1047.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1047.patch",
         "merged_at": null
      },
      "body": null,
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1047/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1047/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   },
   {
      "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1046",
      "repository_url": "https://api.github.com/repos/ethereumbook/ethereumbook",
      "labels_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1046/labels{/name}",
      "comments_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1046/comments",
      "events_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1046/events",
      "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1046",
      "id": 1008630043,
      "node_id": "PR_kwDOA-XO7M4sVlrl",
      "number": 1046,
      "title": "typo fix on word uninitialized",
      "user": {
         "login": "FranciscoPontes",
         "id": 57417441,
         "node_id": "MDQ6VXNlcjU3NDE3NDQx",
         "avatar_url": "https://avatars.githubusercontent.com/u/57417441?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/FranciscoPontes",
         "html_url": "https://github.com/FranciscoPontes",
         "followers_url": "https://api.github.com/users/FranciscoPontes/followers",
         "following_url": "https://api.github.com/users/FranciscoPontes/following{/other_user}",
         "gists_url": "https://api.github.com/users/FranciscoPontes/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/FranciscoPontes/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/FranciscoPontes/subscriptions",
         "organizations_url": "https://api.github.com/users/FranciscoPontes/orgs",
         "repos_url": "https://api.github.com/users/FranciscoPontes/repos",
         "events_url": "https://api.github.com/users/FranciscoPontes/events{/privacy}",
         "received_events_url": "https://api.github.com/users/FranciscoPontes/received_events",
         "type": "User",
         "site_admin": false
      },
      "labels": [],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [],
      "milestone": null,
      "comments": 0,
      "created_at": "2021-09-27T21:25:32Z",
      "updated_at": "2021-09-27T21:25:32Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "draft": false,
      "pull_request": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/pulls/1046",
         "html_url": "https://github.com/ethereumbook/ethereumbook/pull/1046",
         "diff_url": "https://github.com/ethereumbook/ethereumbook/pull/1046.diff",
         "patch_url": "https://github.com/ethereumbook/ethereumbook/pull/1046.patch",
         "merged_at": null
      },
      "body": null,
      "reactions": {
         "url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1046/reactions",
         "total_count": 0,
         "+1": 0,
         "-1": 0,
         "laugh": 0,
         "hooray": 0,
         "confused": 0,
         "heart": 0,
         "rocket": 0,
         "eyes": 0
      },
      "timeline_url": "https://api.github.com/repos/ethereumbook/ethereumbook/issues/1046/timeline",
      "performed_via_github_app": null,
      "state_reason": null
   }
]