import { _GithubUserLikeOwner } from "../models/GithubUserLikeOwner";
import { _SearchResults } from "../models/Search";


export const usersSearch: _SearchResults<_GithubUserLikeOwner> = {
   "total_count": 23330,
   "incomplete_results": false,
   items: [

      {
         "login": "nir",
         "id": 124126,
         "node_id": "MDQ6VXNlcjEyNDEyNg==",
         "avatar_url": "https://avatars.githubusercontent.com/u/124126?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nir",
         "html_url": "https://github.com/nir",
         "followers_url": "https://api.github.com/users/nir/followers",
         "following_url": "https://api.github.com/users/nir/following{/other_user}",
         "gists_url": "https://api.github.com/users/nir/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nir/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nir/subscriptions",
         "organizations_url": "https://api.github.com/users/nir/orgs",
         "repos_url": "https://api.github.com/users/nir/repos",
         "events_url": "https://api.github.com/users/nir/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nir/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirkaufman",
         "id": 2496253,
         "node_id": "MDQ6VXNlcjI0OTYyNTM=",
         "avatar_url": "https://avatars.githubusercontent.com/u/2496253?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirkaufman",
         "html_url": "https://github.com/nirkaufman",
         "followers_url": "https://api.github.com/users/nirkaufman/followers",
         "following_url": "https://api.github.com/users/nirkaufman/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirkaufman/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirkaufman/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirkaufman/subscriptions",
         "organizations_url": "https://api.github.com/users/nirkaufman/orgs",
         "repos_url": "https://api.github.com/users/nirkaufman/repos",
         "events_url": "https://api.github.com/users/nirkaufman/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirkaufman/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirikshan",
         "id": 27781302,
         "node_id": "MDQ6VXNlcjI3NzgxMzAy",
         "avatar_url": "https://avatars.githubusercontent.com/u/27781302?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirikshan",
         "html_url": "https://github.com/nirikshan",
         "followers_url": "https://api.github.com/users/nirikshan/followers",
         "following_url": "https://api.github.com/users/nirikshan/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirikshan/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirikshan/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirikshan/subscriptions",
         "organizations_url": "https://api.github.com/users/nirikshan/orgs",
         "repos_url": "https://api.github.com/users/nirikshan/repos",
         "events_url": "https://api.github.com/users/nirikshan/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirikshan/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirlipo",
         "id": 861782,
         "node_id": "MDQ6VXNlcjg2MTc4Mg==",
         "avatar_url": "https://avatars.githubusercontent.com/u/861782?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirlipo",
         "html_url": "https://github.com/nirlipo",
         "followers_url": "https://api.github.com/users/nirlipo/followers",
         "following_url": "https://api.github.com/users/nirlipo/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirlipo/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirlipo/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirlipo/subscriptions",
         "organizations_url": "https://api.github.com/users/nirlipo/orgs",
         "repos_url": "https://api.github.com/users/nirlipo/repos",
         "events_url": "https://api.github.com/users/nirlipo/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirlipo/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "galnir",
         "id": 36937694,
         "node_id": "MDQ6VXNlcjM2OTM3Njk0",
         "avatar_url": "https://avatars.githubusercontent.com/u/36937694?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/galnir",
         "html_url": "https://github.com/galnir",
         "followers_url": "https://api.github.com/users/galnir/followers",
         "following_url": "https://api.github.com/users/galnir/following{/other_user}",
         "gists_url": "https://api.github.com/users/galnir/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/galnir/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/galnir/subscriptions",
         "organizations_url": "https://api.github.com/users/galnir/orgs",
         "repos_url": "https://api.github.com/users/galnir/repos",
         "events_url": "https://api.github.com/users/galnir/events{/privacy}",
         "received_events_url": "https://api.github.com/users/galnir/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirizr",
         "id": 3631703,
         "node_id": "MDQ6VXNlcjM2MzE3MDM=",
         "avatar_url": "https://avatars.githubusercontent.com/u/3631703?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirizr",
         "html_url": "https://github.com/nirizr",
         "followers_url": "https://api.github.com/users/nirizr/followers",
         "following_url": "https://api.github.com/users/nirizr/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirizr/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirizr/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirizr/subscriptions",
         "organizations_url": "https://api.github.com/users/nirizr/orgs",
         "repos_url": "https://api.github.com/users/nirizr/repos",
         "events_url": "https://api.github.com/users/nirizr/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirizr/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "Plutoberth",
         "id": 26381287,
         "node_id": "MDQ6VXNlcjI2MzgxMjg3",
         "avatar_url": "https://avatars.githubusercontent.com/u/26381287?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/Plutoberth",
         "html_url": "https://github.com/Plutoberth",
         "followers_url": "https://api.github.com/users/Plutoberth/followers",
         "following_url": "https://api.github.com/users/Plutoberth/following{/other_user}",
         "gists_url": "https://api.github.com/users/Plutoberth/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/Plutoberth/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/Plutoberth/subscriptions",
         "organizations_url": "https://api.github.com/users/Plutoberth/orgs",
         "repos_url": "https://api.github.com/users/Plutoberth/repos",
         "events_url": "https://api.github.com/users/Plutoberth/events{/privacy}",
         "received_events_url": "https://api.github.com/users/Plutoberth/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "NirantK",
         "id": 3250749,
         "node_id": "MDQ6VXNlcjMyNTA3NDk=",
         "avatar_url": "https://avatars.githubusercontent.com/u/3250749?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/NirantK",
         "html_url": "https://github.com/NirantK",
         "followers_url": "https://api.github.com/users/NirantK/followers",
         "following_url": "https://api.github.com/users/NirantK/following{/other_user}",
         "gists_url": "https://api.github.com/users/NirantK/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/NirantK/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/NirantK/subscriptions",
         "organizations_url": "https://api.github.com/users/NirantK/orgs",
         "repos_url": "https://api.github.com/users/NirantK/repos",
         "events_url": "https://api.github.com/users/NirantK/events{/privacy}",
         "received_events_url": "https://api.github.com/users/NirantK/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirgn975",
         "id": 3472902,
         "node_id": "MDQ6VXNlcjM0NzI5MDI=",
         "avatar_url": "https://avatars.githubusercontent.com/u/3472902?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirgn975",
         "html_url": "https://github.com/nirgn975",
         "followers_url": "https://api.github.com/users/nirgn975/followers",
         "following_url": "https://api.github.com/users/nirgn975/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirgn975/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirgn975/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirgn975/subscriptions",
         "organizations_url": "https://api.github.com/users/nirgn975/orgs",
         "repos_url": "https://api.github.com/users/nirgn975/repos",
         "events_url": "https://api.github.com/users/nirgn975/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirgn975/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "niranjan94",
         "id": 2404372,
         "node_id": "MDQ6VXNlcjI0MDQzNzI=",
         "avatar_url": "https://avatars.githubusercontent.com/u/2404372?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/niranjan94",
         "html_url": "https://github.com/niranjan94",
         "followers_url": "https://api.github.com/users/niranjan94/followers",
         "following_url": "https://api.github.com/users/niranjan94/following{/other_user}",
         "gists_url": "https://api.github.com/users/niranjan94/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/niranjan94/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/niranjan94/subscriptions",
         "organizations_url": "https://api.github.com/users/niranjan94/orgs",
         "repos_url": "https://api.github.com/users/niranjan94/repos",
         "events_url": "https://api.github.com/users/niranjan94/events{/privacy}",
         "received_events_url": "https://api.github.com/users/niranjan94/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirvdrum",
         "id": 12584,
         "node_id": "MDQ6VXNlcjEyNTg0",
         "avatar_url": "https://avatars.githubusercontent.com/u/12584?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirvdrum",
         "html_url": "https://github.com/nirvdrum",
         "followers_url": "https://api.github.com/users/nirvdrum/followers",
         "following_url": "https://api.github.com/users/nirvdrum/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirvdrum/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirvdrum/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirvdrum/subscriptions",
         "organizations_url": "https://api.github.com/users/nirvdrum/orgs",
         "repos_url": "https://api.github.com/users/nirvdrum/repos",
         "events_url": "https://api.github.com/users/nirvdrum/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirvdrum/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "NirmalSilwal",
         "id": 31946761,
         "node_id": "MDQ6VXNlcjMxOTQ2NzYx",
         "avatar_url": "https://avatars.githubusercontent.com/u/31946761?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/NirmalSilwal",
         "html_url": "https://github.com/NirmalSilwal",
         "followers_url": "https://api.github.com/users/NirmalSilwal/followers",
         "following_url": "https://api.github.com/users/NirmalSilwal/following{/other_user}",
         "gists_url": "https://api.github.com/users/NirmalSilwal/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/NirmalSilwal/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/NirmalSilwal/subscriptions",
         "organizations_url": "https://api.github.com/users/NirmalSilwal/orgs",
         "repos_url": "https://api.github.com/users/NirmalSilwal/repos",
         "events_url": "https://api.github.com/users/NirmalSilwal/events{/privacy}",
         "received_events_url": "https://api.github.com/users/NirmalSilwal/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirzaf",
         "id": 18024930,
         "node_id": "MDQ6VXNlcjE4MDI0OTMw",
         "avatar_url": "https://avatars.githubusercontent.com/u/18024930?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirzaf",
         "html_url": "https://github.com/nirzaf",
         "followers_url": "https://api.github.com/users/nirzaf/followers",
         "following_url": "https://api.github.com/users/nirzaf/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirzaf/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirzaf/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirzaf/subscriptions",
         "organizations_url": "https://api.github.com/users/nirzaf/orgs",
         "repos_url": "https://api.github.com/users/nirzaf/repos",
         "events_url": "https://api.github.com/users/nirzaf/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirzaf/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirum",
         "id": 904854,
         "node_id": "MDQ6VXNlcjkwNDg1NA==",
         "avatar_url": "https://avatars.githubusercontent.com/u/904854?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirum",
         "html_url": "https://github.com/nirum",
         "followers_url": "https://api.github.com/users/nirum/followers",
         "following_url": "https://api.github.com/users/nirum/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirum/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirum/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirum/subscriptions",
         "organizations_url": "https://api.github.com/users/nirum/orgs",
         "repos_url": "https://api.github.com/users/nirum/repos",
         "events_url": "https://api.github.com/users/nirum/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirum/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirs",
         "id": 395026,
         "node_id": "MDQ6VXNlcjM5NTAyNg==",
         "avatar_url": "https://avatars.githubusercontent.com/u/395026?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirs",
         "html_url": "https://github.com/nirs",
         "followers_url": "https://api.github.com/users/nirs/followers",
         "following_url": "https://api.github.com/users/nirs/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirs/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirs/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirs/subscriptions",
         "organizations_url": "https://api.github.com/users/nirs/orgs",
         "repos_url": "https://api.github.com/users/nirs/repos",
         "events_url": "https://api.github.com/users/nirs/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirs/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirgeier",
         "id": 555154,
         "node_id": "MDQ6VXNlcjU1NTE1NA==",
         "avatar_url": "https://avatars.githubusercontent.com/u/555154?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirgeier",
         "html_url": "https://github.com/nirgeier",
         "followers_url": "https://api.github.com/users/nirgeier/followers",
         "following_url": "https://api.github.com/users/nirgeier/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirgeier/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirgeier/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirgeier/subscriptions",
         "organizations_url": "https://api.github.com/users/nirgeier/orgs",
         "repos_url": "https://api.github.com/users/nirgeier/repos",
         "events_url": "https://api.github.com/users/nirgeier/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirgeier/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirsarkar",
         "id": 20984194,
         "node_id": "MDQ6VXNlcjIwOTg0MTk0",
         "avatar_url": "https://avatars.githubusercontent.com/u/20984194?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirsarkar",
         "html_url": "https://github.com/nirsarkar",
         "followers_url": "https://api.github.com/users/nirsarkar/followers",
         "following_url": "https://api.github.com/users/nirsarkar/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirsarkar/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirsarkar/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirsarkar/subscriptions",
         "organizations_url": "https://api.github.com/users/nirsarkar/orgs",
         "repos_url": "https://api.github.com/users/nirsarkar/repos",
         "events_url": "https://api.github.com/users/nirsarkar/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirsarkar/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirbhayvashisht",
         "id": 37499329,
         "node_id": "MDQ6VXNlcjM3NDk5MzI5",
         "avatar_url": "https://avatars.githubusercontent.com/u/37499329?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirbhayvashisht",
         "html_url": "https://github.com/nirbhayvashisht",
         "followers_url": "https://api.github.com/users/nirbhayvashisht/followers",
         "following_url": "https://api.github.com/users/nirbhayvashisht/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirbhayvashisht/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirbhayvashisht/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirbhayvashisht/subscriptions",
         "organizations_url": "https://api.github.com/users/nirbhayvashisht/orgs",
         "repos_url": "https://api.github.com/users/nirbhayvashisht/repos",
         "events_url": "https://api.github.com/users/nirbhayvashisht/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirbhayvashisht/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "Nirma",
         "id": 882822,
         "node_id": "MDQ6VXNlcjg4MjgyMg==",
         "avatar_url": "https://avatars.githubusercontent.com/u/882822?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/Nirma",
         "html_url": "https://github.com/Nirma",
         "followers_url": "https://api.github.com/users/Nirma/followers",
         "following_url": "https://api.github.com/users/Nirma/following{/other_user}",
         "gists_url": "https://api.github.com/users/Nirma/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/Nirma/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/Nirma/subscriptions",
         "organizations_url": "https://api.github.com/users/Nirma/orgs",
         "repos_url": "https://api.github.com/users/Nirma/repos",
         "events_url": "https://api.github.com/users/Nirma/events{/privacy}",
         "received_events_url": "https://api.github.com/users/Nirma/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirajgeorgian",
         "id": 12744740,
         "node_id": "MDQ6VXNlcjEyNzQ0NzQw",
         "avatar_url": "https://avatars.githubusercontent.com/u/12744740?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirajgeorgian",
         "html_url": "https://github.com/nirajgeorgian",
         "followers_url": "https://api.github.com/users/nirajgeorgian/followers",
         "following_url": "https://api.github.com/users/nirajgeorgian/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirajgeorgian/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirajgeorgian/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirajgeorgian/subscriptions",
         "organizations_url": "https://api.github.com/users/nirajgeorgian/orgs",
         "repos_url": "https://api.github.com/users/nirajgeorgian/repos",
         "events_url": "https://api.github.com/users/nirajgeorgian/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirajgeorgian/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirajsonawane",
         "id": 11003095,
         "node_id": "MDQ6VXNlcjExMDAzMDk1",
         "avatar_url": "https://avatars.githubusercontent.com/u/11003095?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirajsonawane",
         "html_url": "https://github.com/nirajsonawane",
         "followers_url": "https://api.github.com/users/nirajsonawane/followers",
         "following_url": "https://api.github.com/users/nirajsonawane/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirajsonawane/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirajsonawane/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirajsonawane/subscriptions",
         "organizations_url": "https://api.github.com/users/nirajsonawane/orgs",
         "repos_url": "https://api.github.com/users/nirajsonawane/repos",
         "events_url": "https://api.github.com/users/nirajsonawane/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirajsonawane/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nir0s",
         "id": 2003076,
         "node_id": "MDQ6VXNlcjIwMDMwNzY=",
         "avatar_url": "https://avatars.githubusercontent.com/u/2003076?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nir0s",
         "html_url": "https://github.com/nir0s",
         "followers_url": "https://api.github.com/users/nir0s/followers",
         "following_url": "https://api.github.com/users/nir0s/following{/other_user}",
         "gists_url": "https://api.github.com/users/nir0s/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nir0s/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nir0s/subscriptions",
         "organizations_url": "https://api.github.com/users/nir0s/orgs",
         "repos_url": "https://api.github.com/users/nir0s/repos",
         "events_url": "https://api.github.com/users/nir0s/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nir0s/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirlanka",
         "id": 7931869,
         "node_id": "MDQ6VXNlcjc5MzE4Njk=",
         "avatar_url": "https://avatars.githubusercontent.com/u/7931869?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirlanka",
         "html_url": "https://github.com/nirlanka",
         "followers_url": "https://api.github.com/users/nirlanka/followers",
         "following_url": "https://api.github.com/users/nirlanka/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirlanka/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirlanka/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirlanka/subscriptions",
         "organizations_url": "https://api.github.com/users/nirlanka/orgs",
         "repos_url": "https://api.github.com/users/nirlanka/repos",
         "events_url": "https://api.github.com/users/nirlanka/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirlanka/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirinchev",
         "id": 2315687,
         "node_id": "MDQ6VXNlcjIzMTU2ODc=",
         "avatar_url": "https://avatars.githubusercontent.com/u/2315687?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirinchev",
         "html_url": "https://github.com/nirinchev",
         "followers_url": "https://api.github.com/users/nirinchev/followers",
         "following_url": "https://api.github.com/users/nirinchev/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirinchev/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirinchev/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirinchev/subscriptions",
         "organizations_url": "https://api.github.com/users/nirinchev/orgs",
         "repos_url": "https://api.github.com/users/nirinchev/repos",
         "events_url": "https://api.github.com/users/nirinchev/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirinchev/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirev",
         "id": 686510,
         "node_id": "MDQ6VXNlcjY4NjUxMA==",
         "avatar_url": "https://avatars.githubusercontent.com/u/686510?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirev",
         "html_url": "https://github.com/nirev",
         "followers_url": "https://api.github.com/users/nirev/followers",
         "following_url": "https://api.github.com/users/nirev/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirev/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirev/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirev/subscriptions",
         "organizations_url": "https://api.github.com/users/nirev/orgs",
         "repos_url": "https://api.github.com/users/nirev/repos",
         "events_url": "https://api.github.com/users/nirev/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirev/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "NiranjanNlc",
         "id": 25600880,
         "node_id": "MDQ6VXNlcjI1NjAwODgw",
         "avatar_url": "https://avatars.githubusercontent.com/u/25600880?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/NiranjanNlc",
         "html_url": "https://github.com/NiranjanNlc",
         "followers_url": "https://api.github.com/users/NiranjanNlc/followers",
         "following_url": "https://api.github.com/users/NiranjanNlc/following{/other_user}",
         "gists_url": "https://api.github.com/users/NiranjanNlc/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/NiranjanNlc/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/NiranjanNlc/subscriptions",
         "organizations_url": "https://api.github.com/users/NiranjanNlc/orgs",
         "repos_url": "https://api.github.com/users/NiranjanNlc/repos",
         "events_url": "https://api.github.com/users/NiranjanNlc/events{/privacy}",
         "received_events_url": "https://api.github.com/users/NiranjanNlc/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "Nirmitjatana",
         "id": 52108077,
         "node_id": "MDQ6VXNlcjUyMTA4MDc3",
         "avatar_url": "https://avatars.githubusercontent.com/u/52108077?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/Nirmitjatana",
         "html_url": "https://github.com/Nirmitjatana",
         "followers_url": "https://api.github.com/users/Nirmitjatana/followers",
         "following_url": "https://api.github.com/users/Nirmitjatana/following{/other_user}",
         "gists_url": "https://api.github.com/users/Nirmitjatana/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/Nirmitjatana/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/Nirmitjatana/subscriptions",
         "organizations_url": "https://api.github.com/users/Nirmitjatana/orgs",
         "repos_url": "https://api.github.com/users/Nirmitjatana/repos",
         "events_url": "https://api.github.com/users/Nirmitjatana/events{/privacy}",
         "received_events_url": "https://api.github.com/users/Nirmitjatana/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "Niranjankumar-c",
         "id": 36450263,
         "node_id": "MDQ6VXNlcjM2NDUwMjYz",
         "avatar_url": "https://avatars.githubusercontent.com/u/36450263?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/Niranjankumar-c",
         "html_url": "https://github.com/Niranjankumar-c",
         "followers_url": "https://api.github.com/users/Niranjankumar-c/followers",
         "following_url": "https://api.github.com/users/Niranjankumar-c/following{/other_user}",
         "gists_url": "https://api.github.com/users/Niranjankumar-c/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/Niranjankumar-c/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/Niranjankumar-c/subscriptions",
         "organizations_url": "https://api.github.com/users/Niranjankumar-c/orgs",
         "repos_url": "https://api.github.com/users/Niranjankumar-c/repos",
         "events_url": "https://api.github.com/users/Niranjankumar-c/events{/privacy}",
         "received_events_url": "https://api.github.com/users/Niranjankumar-c/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "nirmal-suthar",
         "id": 46129963,
         "node_id": "MDQ6VXNlcjQ2MTI5OTYz",
         "avatar_url": "https://avatars.githubusercontent.com/u/46129963?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/nirmal-suthar",
         "html_url": "https://github.com/nirmal-suthar",
         "followers_url": "https://api.github.com/users/nirmal-suthar/followers",
         "following_url": "https://api.github.com/users/nirmal-suthar/following{/other_user}",
         "gists_url": "https://api.github.com/users/nirmal-suthar/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/nirmal-suthar/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/nirmal-suthar/subscriptions",
         "organizations_url": "https://api.github.com/users/nirmal-suthar/orgs",
         "repos_url": "https://api.github.com/users/nirmal-suthar/repos",
         "events_url": "https://api.github.com/users/nirmal-suthar/events{/privacy}",
         "received_events_url": "https://api.github.com/users/nirmal-suthar/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      },
      {
         "login": "niryariv",
         "id": 1771,
         "node_id": "MDQ6VXNlcjE3NzE=",
         "avatar_url": "https://avatars.githubusercontent.com/u/1771?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/niryariv",
         "html_url": "https://github.com/niryariv",
         "followers_url": "https://api.github.com/users/niryariv/followers",
         "following_url": "https://api.github.com/users/niryariv/following{/other_user}",
         "gists_url": "https://api.github.com/users/niryariv/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/niryariv/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/niryariv/subscriptions",
         "organizations_url": "https://api.github.com/users/niryariv/orgs",
         "repos_url": "https://api.github.com/users/niryariv/repos",
         "events_url": "https://api.github.com/users/niryariv/events{/privacy}",
         "received_events_url": "https://api.github.com/users/niryariv/received_events",
         "type": "User",
         "site_admin": false,
         "score": 1
      }
   ]
}
