import { AppProps } from 'next/dist/shared/lib/router/router'
import Head from 'next/head'
import { useEffect } from 'react'
import { useSubject, useBehaviorSubject } from 'use-rxjs-state'
import { AppContextProvider } from '../context/app.context'
import { ThemeContextProvider } from '../context/theme.context'
import '../styles/globals.css'


function MyApp({ Component, pageProps }: AppProps): JSX.Element {

  return <>
    <Head>
      <title>Top</title>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <ThemeContextProvider>
      <AppContextProvider>
        <Component {...pageProps} />
      </AppContextProvider>
    </ThemeContextProvider>
  </>
}

export default MyApp
